# Generated by Django 5.1.3 on 2024-11-28 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hierarchy',
            fields=[
                ('hierar_id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='JerarquíaID')),
                ('hierar_name', models.CharField(max_length=150, unique=True, verbose_name='Nombre de Jerarquía')),
                ('hierar_description', models.TextField(verbose_name='Descripción de Jerarquía')),
                ('hierar_icon', models.CharField(blank=True, max_length=100, null=True, verbose_name='Icono de Jerarquía')),
                ('hierar_sup', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='products.hierarchy', verbose_name='Jerarquía Superior')),
            ],
            options={
                'verbose_name': 'Hierarchy',
                'verbose_name_plural': 'Hierarchies',
                'db_table': 'Hierarchy',
                'ordering': ('hierar_id',),
            },
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('val_id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ValorID')),
                ('val_name', models.CharField(max_length=150, verbose_name='Nombre de Valor')),
                ('val_description', models.TextField(blank=True, null=True, verbose_name='Descripción de valor')),
                ('val_icon', models.CharField(blank=True, max_length=100, null=True, verbose_name='Icono')),
                ('val_order', models.IntegerField(default=0, verbose_name='Orden')),
                ('hierar_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='products.hierarchy', verbose_name='JerarquíaID')),
                ('val_sup', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='products.value', verbose_name='Valor Superior')),
            ],
            options={
                'verbose_name': 'Value',
                'verbose_name_plural': 'Values',
                'db_table': 'Value',
                'ordering': ('val_id', 'hierar_id'),
                'constraints': [models.UniqueConstraint(fields=('val_sup', 'hierar_id', 'val_name'), name='unique_hierar_sup_name')],
            },
        ),
    ]
