# Generated by Django 5.1.3 on 2024-11-29 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pdt_id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ProductoID')),
                ('pdt_model', models.CharField(max_length=200, verbose_name='Modelo del Producto')),
                ('pdt_name', models.CharField(max_length=200, verbose_name='Nombre del Producto')),
                ('pdt_serial', models.CharField(max_length=15, unique=True, verbose_name='Serial del Producto')),
                ('pdt_stock', models.PositiveIntegerField(verbose_name='Cantidad del Producto')),
                ('pdt_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio del Producto')),
                ('pdt_description', models.TextField(blank=True, null=True, verbose_name='Descripcion del Producto')),
                ('pdt_image', models.ImageField(default='product/img/img.png', upload_to='product/img/', verbose_name='Imagen del Producto')),
                ('id_brand', models.ForeignKey(default=0, limit_choices_to=models.Q(('hierar_id', 12), ('hierar_id', 0), _connector='OR'), on_delete=django.db.models.deletion.PROTECT, related_name='PDT_id_brand', to='products.value')),
                ('id_category', models.ForeignKey(default=0, limit_choices_to=models.Q(('hierar_id', 11), ('hierar_id', 0), _connector='OR'), on_delete=django.db.models.deletion.PROTECT, related_name='PDT_id_category', to='products.value')),
                ('id_product', models.ForeignKey(default=0, limit_choices_to=models.Q(('hierar_id', 10), ('hierar_id', 0), _connector='OR'), on_delete=django.db.models.deletion.PROTECT, related_name='PDT_id_product', to='products.value')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'Product',
                'ordering': ('pdt_id',),
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('sale_id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='VentaID')),
                ('sale_quantity', models.PositiveIntegerField(verbose_name='Cantidad a Vender')),
                ('sale_date', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('product_id', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.PROTECT, related_name='sale_product', to='products.product', verbose_name='ProductoID')),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
                'db_table': 'Sale',
                'ordering': ('sale_id',),
            },
        ),
    ]
