# Generated by Django 5.1.3 on 2025-01-11 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_product_sale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='user/img/defaul-user.png', upload_to='user/img/', verbose_name='Imagen de Perfil')),
                ('gender', models.OneToOneField(limit_choices_to=models.Q(('hierar_id', 13)), on_delete=django.db.models.deletion.PROTECT, related_name='profile_id_gender', to='products.value')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='profile_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
