# Generated by Django 5.1.3 on 2025-01-12 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='user/img/default-user.webp', upload_to='user/img/', verbose_name='Imagen de Perfil'),
        ),
    ]
