# Generated by Django 5.1.3 on 2025-01-12 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0002_alter_profile_image'),
        ('products', '0002_product_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.OneToOneField(limit_choices_to=models.Q(('hierar_id', 13)), null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profile_id_gender', to='products.value'),
        ),
    ]
