# Generated by Django 5.1.3 on 2025-03-01 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0003_alter_profile_gender'),
        ('products', '0002_product_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.ForeignKey(default=1, limit_choices_to=models.Q(('hierar_id', 13), ('hierar_id', 0), _connector='OR'), on_delete=django.db.models.deletion.PROTECT, related_name='profile_id_gender', to='products.value'),
        ),
    ]
